image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME


stages:
  - build
  - deploy

variables:
  SERVER_SSH_PRIVATE_KEY: "$SERVER_SSH_PRIVATE_KEY"

build:
  stage: build
  script:
    - ./gradlew build -x test

deploy_to_server:
  stage: deploy
  script:
    - apk update && apk add openssh-client 
    - scp -o StrictHostKeyChecking=no -r ./build/libs/Eventichs_API-0.0.1.jar gitlab@v34l.com:/Dev/Eventichs/eventichs_api
    - $SERVER_SSH_PRIVATE_KEY
    - ssh serv@123.123.123.5 'bash -s' <<EOF
        cd /Dev/Eventichs/eventichs_api
        ./gradlew bootRun > /dev/null 2>&1 &
      EOF
