auth0:
  audience: http://eventichs.api/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-xa2f6qcrb7kap33n.us.auth0.com/
logging:
  level:
    org.springframework.security.web: DEBUG